# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order-service/orderservice.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 3, "", "order-service/orderservice.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n order-service/orderservice.proto\x12\x0corderservice\x1a\x1fgoogle/protobuf/timestamp.proto"\xc5\x01\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12.\n\norder_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x04meal\x18\x03 \x03(\x0b\x32\x1d.orderservice.Order.MealEntry\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x02\x1a?\n\tMealEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.orderservice.Meal:\x02\x38\x01"s\n\x04Meal\x12$\n\x06\x65ntree\x18\x01 \x01(\x0b\x32\x14.orderservice.Entree\x12"\n\x05\x64rink\x18\x02 \x01(\x0b\x32\x13.orderservice.Drink\x12!\n\x05sides\x18\x03 \x03(\x0b\x32\x12.orderservice.Side"G\n\x06\x45ntree\x12\x0c\n\x04\x66ood\x18\x01 \x01(\t\x12\r\n\x05notes\x18\x02 \x03(\t\x12 \n\x04size\x18\x03 \x01(\x0e\x32\x12.orderservice.Size"7\n\x05\x44rink\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x04size\x18\x02 \x01(\x0e\x32\x12.orderservice.Size"E\n\x04Side\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05notes\x18\x02 \x03(\t\x12 \n\x04size\x18\x03 \x01(\x0e\x32\x12.orderservice.Size*M\n\x04Size\x12\x14\n\x10Size_UNSPECIFIED\x10\x00\x12\x0e\n\nSize_SMALL\x10\x01\x12\x0f\n\x0bSize_MEDIUM\x10\x02\x12\x0e\n\nSize_LARGE\x10\x03\x42\tZ\x07\x64ist/pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "order_service.orderservice_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\007dist/pb"
    _globals["_ORDER_MEALENTRY"]._loaded_options = None
    _globals["_ORDER_MEALENTRY"]._serialized_options = b"8\001"
    _globals["_SIZE"]._serialized_start = 601
    _globals["_SIZE"]._serialized_end = 678
    _globals["_ORDER"]._serialized_start = 84
    _globals["_ORDER"]._serialized_end = 281
    _globals["_ORDER_MEALENTRY"]._serialized_start = 218
    _globals["_ORDER_MEALENTRY"]._serialized_end = 281
    _globals["_MEAL"]._serialized_start = 283
    _globals["_MEAL"]._serialized_end = 398
    _globals["_ENTREE"]._serialized_start = 400
    _globals["_ENTREE"]._serialized_end = 471
    _globals["_DRINK"]._serialized_start = 473
    _globals["_DRINK"]._serialized_end = 528
    _globals["_SIDE"]._serialized_start = 530
    _globals["_SIDE"]._serialized_end = 599
# @@protoc_insertion_point(module_scope)
